language: node_js
node_js: "8"
cache:
directories:
    - "node_modules"
install:
  - npm install
services:
  - mysql

env:
  global:
  - NODE_ENV=test

before_script:
  - npm run build
  - npm install -g sequelize-cli
  - npm install mysql2 -g
  - sequelize db:migrate
script:
  - npm test
after_success:
  - npm run coverage

